'use client';

import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { BellRing, BookOpen, CheckCircle2, ClipboardList, GraduationCap, LogOut, Mail, Plus, Star } from 'lucide-react';
import './coursework.css';

type ReviewState = 'not_done'|'half_done'|'done';
const reviewLabel:Record<ReviewState,string>={not_done:'Not Done',half_done:'Half Done',done:'Done'};
const reviewStatus:Record<ReviewState,'pending'|'half_done'|'completed'>={not_done:'pending',half_done:'half_done',done:'completed'};
type Work = {review_state:ReviewState;id:string;student_id:string;student_name:string;kind:string;subject:string;title:string;instructions:string;due_date:string;source_id:string|null;source_url:string;status:string;score:number|null;remarks:string;submission:string;submitted_at:string|null;reviewed_at:string|null;created_at:string;updated_at:string;assignments?:Work[];student_count?:number};
type Data = {role:string;items:Work[];students:{id:string;username:string}[];subjects:string[]};
type Draft = {student_id:string;kind:string;subject:string;title:string;instructions:string;due_date:string;source_id:string|null};
function tomorrow() {const date = new Date(new Date().toLocaleString('en-US', {timeZone:'Asia/Dhaka'}));date.setDate(date.getDate()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
const dateLabel=(value:string)=>new Date(value.includes('T')?value:`${value}T12:00:00+06:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Dhaka'});
const localDay=(value:string)=>new Intl.DateTimeFormat('sv-SE',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Dhaka'}).format(new Date(value));
const latestSubmission=(group:Work[])=>group.map(item=>item.submitted_at).filter((value):value is string=>!!value).sort().at(-1);
const emptyDraft = ():Draft => ({student_id:'',kind:'Homework',subject:'Mathematics',title:'',instructions:'',due_date:tomorrow(),source_id:null});
async function request(path:string, method='GET', body?:unknown) {
 const response = await fetch(`/api/coursework${path}`, {method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
 const value = await response.json();
 if (!response.ok) throw new Error(value.error || (response.status===422?'Check the fields and try again.':'Unable to load your work.'));
 return value;
}
function Stars({value,onChange}:{value:number|null;onChange?:(score:number|null)=>void}) {
 const [hover,setHover]=useState<number|null>(null);
 return <div className="cw-rating"><div className="cw-stars" role={onChange?'group':'img'} aria-label={`Rating: ${value??'not rated'} out of 10`} onMouseLeave={()=>setHover(null)}>{Array.from({length:10},(_,i)=>onChange?<button key={i} type="button" aria-label={`Rate ${i+1} out of 10`} aria-pressed={value===i+1} onFocus={()=>setHover(i+1)} onBlur={()=>setHover(null)} onMouseEnter={()=>setHover(i+1)} onClick={()=>onChange(i+1)}><Star size={20} fill={i<(hover??value??0)?'currentColor':'none'}/></button>:<Star key={i} size={17} fill={i<(value??0)?'currentColor':'none'}/> )}</div><span>{hover??value??'—'}/10</span>{onChange&&value!==null&&<button type="button" className="cw-text-button" onClick={()=>onChange(null)}>Clear</button>}</div>;
}
function WorkCard({item,teacher,reload,edit,notify}:{item:Work;teacher:boolean;reload:()=>Promise<void>;edit:(item:Work)=>void;notify:(message:string)=>void}) {
 const [status,setStatus]=useState<ReviewState>(item.review_state),[score,setScore]=useState(item.score),[remarks,setRemarks]=useState(''),[submission,setSubmission]=useState(item.submission),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function run(path:string,method:string,body:unknown,success:string) {setBusy(true);setError('');setMessage('');try {const result=await request(path,method,body);setMessage(result.message||success);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveReview(){
  setBusy(true);setError('');setMessage('');
  let reviewSaved=false;
  try{
   await request(`/${item.id}/review`,'PUT',{status:reviewStatus[status],score,remarks:remarks.trim()||item.remarks});
   reviewSaved=true;
   await request(`/${item.id}/email`,'POST');
   setRemarks('');notify('Guardian has been notified. Review saved.');await reload();
  }catch(caught){setError(`${reviewSaved?'Review saved, but Guardian has not been notified. ':''}${(caught as Error).message}`);}
  finally{setBusy(false);}
 }
 return <article className={`cw-card cw-subject-${item.subject.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}><div className="cw-card-top"><span className="cw-subject">{teacher?item.student_name:item.subject}</span><span className={`cw-status ${teacher?item.review_state:item.status}`}>{teacher?reviewLabel[item.review_state]:item.status==='completed'?'Completed':item.submitted_at&&!item.reviewed_at?'Awaiting review':'Pending'}</span></div>{!teacher&&<><h3>{item.title}</h3><p className="cw-meta">{item.kind} · Due {item.due_date}</p><p className="cw-copy">{item.instructions||'Follow your teacher’s instructions.'}</p></>}{item.source_url&&<a className="cw-source" href={item.source_url} target="_blank" rel="noreferrer">Open original Notion work ↗</a>}
 {item.submitted_at&&<div className="cw-submission"><strong>Student submission</strong><p>{item.submission}</p><small>Submitted {new Date(item.submitted_at).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})}</small></div>}
 {teacher?<form onSubmit={event=>{event.preventDefault();void saveReview();}}><fieldset disabled={busy}><label>Review Status<select value={status} onChange={event=>setStatus(event.target.value as ReviewState)}><option value="not_done">Not Done</option><option value="half_done">Half Done</option><option value="done">Done</option></select></label><label>Mark · 1 lowest, 10 highest</label><Stars value={score} onChange={setScore}/>{item.remarks&&<div className="cw-saved-remarks"><strong>Last saved update</strong><p>{item.remarks}</p></div>}<label>Comments / remarks<textarea maxLength={4000} value={remarks} onChange={event=>setRemarks(event.target.value)} placeholder="Share progress and the next step…"/></label><div className="cw-actions"><button className="cw-primary" type="submit">Save review</button><button type="button" onClick={()=>edit(item)}>Edit task</button><button type="button" onClick={()=>void saveReview()}><Mail size={15}/>Update to Guardian</button></div><small className="cw-help">Saving sends the review and any comments to the Guardian. You can also send an updated review with Update to Guardian.</small></fieldset></form>:<><Stars value={item.score}/>{item.remarks&&<div className="cw-submission"><strong>Teacher remarks</strong><p>{item.remarks}</p></div>}{item.status!=='completed'&&<form onSubmit={event=>{event.preventDefault();void run(`/${item.id}/submission`,'PUT',{submission},'Work submitted for review.');}}><fieldset disabled={busy}><label>Your answer or completed work<textarea required maxLength={10000} value={submission} onChange={event=>setSubmission(event.target.value)} placeholder="Write your answers or describe the work you have completed…"/></label><button className="cw-primary" disabled={!submission.trim()}>{item.submitted_at?'Resubmit work':'Submit work'}</button></fieldset></form>}</>}
 {error&&<p className="cw-error" role="alert">{error}</p>}{message&&<p role="status" className="cw-success">{message}</p>}</article>;
}
function groupTeacherWork(items:Work[]) {
 return items.map(item=>item.assignments||[item]);
}
function DailyFeedback(){
 const [body,setBody]=useState(''),[day,setDay]=useState(''),[previousBody,setPreviousBody]=useState(''),[saved,setSaved]=useState(false),[hasFeedback,setHasFeedback]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[confirmation,setConfirmation]=useState<{before:string;after:string}|null>(null);
 const closeButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{let active=true;void fetch('/api/teacher-feedback/today',{cache:'no-store'}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error||'Could not load today’s update.');if(active){setDay(value.day);setPreviousBody(value.feedback?.body||'');setSaved(!!value.feedback);setHasFeedback(!!value.feedback);}}).catch(caught=>{if(active)setError(caught.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 useEffect(()=>{if(!confirmation)return;closeButton.current?.focus();const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();window.location.reload();}};document.addEventListener('keydown',onKeyDown);return()=>document.removeEventListener('keydown',onKeyDown);},[confirmation]);
 async function save(event:FormEvent){event.preventDefault();if(busy||!body.trim())return;setBusy(true);setError('');try{const response=await fetch('/api/teacher-feedback/today',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Could not send today’s update.');setConfirmation({before:previousBody,after:value.feedback.body});setPreviousBody(value.feedback.body);setDay(value.day);setBody('');setSaved(true);setHasFeedback(true);}catch(caught){setError((caught as Error).message);}finally{setBusy(false);}}
 return <><section className="cw-daily-feedback"><div><span className="cw-eyebrow">DAILY CLASSROOM UPDATE</span><h2>How is Shreehan doing today?</h2><p>Write a note for the admin. Shuvro will see the full text in Notifications.</p></div><form onSubmit={save}><label htmlFor="cw-daily-body">Today’s feedback {day&&<small>· {dateLabel(day)}</small>}</label><textarea id="cw-daily-body" maxLength={5000} required disabled={loading} value={body} onChange={event=>{setBody(event.target.value);setSaved(false);}} placeholder="Share a new update on Shreehan’s progress…"/><div className="cw-feedback-actions"><span role="status">{error|| (loading?'Loading today’s note…':saved?'Saved for admin. The entry box is ready for a new update.':hasFeedback?'Your next update will replace today’s earlier note.':'One note per day; saving again updates it.')}</span><button className="cw-primary" disabled={loading||busy||!body.trim()}>{busy?'Saving…':hasFeedback?'Update feedback':'Send to admin'}</button></div></form></section>{confirmation&&<div className="cw-overlay"><section className="cw-feedback-dialog" role="dialog" aria-modal="true" aria-labelledby="cw-feedback-confirmation-title"><span className="cw-eyebrow">TEACHER UPDATE</span><h2 id="cw-feedback-confirmation-title">{confirmation.before?'Feedback updated':'Feedback sent'}</h2><p>Shuvro can see this update in Notifications.</p>{confirmation.before&&<div className="cw-feedback-dialog-copy"><strong>Previous update</strong><p>{confirmation.before}</p></div>}<div className="cw-feedback-dialog-copy"><strong>{confirmation.before?'New update':'Submitted update'}</strong><p>{confirmation.after}</p></div><button ref={closeButton} className="cw-primary" type="button" onClick={()=>window.location.reload()}>Done</button></section></div>}</>;
}
function TeacherPassword(){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function save(event:FormEvent<HTMLFormElement>){
  event.preventDefault();const form=event.currentTarget;const values=new FormData(form);
  const new_password=String(values.get('new_password')||'');
  if(new_password!==values.get('confirm_password')){setError('Passwords do not match.');return;}
  setBusy(true);setError('');setMessage('');
  try{const response=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password,confirm_password:new_password})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not change password.');form.reset();setMessage('Password changed. Your other sessions were closed.');}
  catch(caught){setError((caught as Error).message);}finally{setBusy(false);}
 }
 return <div className="cw-password"><button type="button" aria-expanded={open} aria-controls="cw-password-panel" onClick={()=>setOpen(!open)}>Change password</button>{open&&<section id="cw-password-panel" className="cw-password-panel" aria-label="Change password"><div className="cw-password-heading"><h2>Change password</h2><button type="button" onClick={()=>setOpen(false)} aria-label="Close password form">×</button></div><form onSubmit={save}><label>New password<input name="new_password" type="password" autoComplete="new-password" minLength={6} maxLength={256} required/></label><label>Confirm password<input name="confirm_password" type="password" autoComplete="new-password" minLength={6} maxLength={256} required/></label><button className="cw-primary" disabled={busy}>{busy?'Saving…':'Save password'}</button>{error&&<p className="cw-error" role="alert">{error}</p>}{message&&<p className="cw-success" role="status">{message}</p>}</form></section>}</div>;
}
export default function Coursework() {
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[calendarDate,setCalendarDate]=useState(''),[filter,setFilter]=useState('All'),[teacherStatus,setTeacherStatus]=useState<ReviewState|''>(''),[toast,setToast]=useState(''),[kind,setKind]=useState('All'),[formOpen,setFormOpen]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[deletingId,setDeletingId]=useState<string|null>(null);
 const dialogRef=useRef<HTMLElement>(null);
 const workRef=useRef<HTMLElement>(null);
 const savingRef=useRef(false);
 useEffect(()=>{setCalendarDate(localDay(new Date().toISOString()));},[]);
 useEffect(()=>{
  if(!formOpen)return;
  const previous=document.activeElement as HTMLElement|null;
  const overflow=document.body.style.overflow;
  document.body.style.overflow='hidden';
  const handle=(event:KeyboardEvent)=>{
   if(event.key==='Escape'&&!busy){event.preventDefault();setFormOpen(false);}
   if(event.key==='Tab'){
    const nodes=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]');
    if(!nodes?.length)return;
    const first=nodes[0],last=nodes[nodes.length-1];
    if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
    else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
   }
  };
  document.addEventListener('keydown',handle);
  return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handle);previous?.focus();};
 },[formOpen,busy]);
 const reload=useCallback(async()=>{const value=await request('');setData(value);setError('');},[]);
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[reload]);
 const teacher=data?.role==='teacher';
 function change(key:keyof Draft,value:string|null){setDraft(d=>({...d,[key]:value}));}
 function start(item?:Work){setEditing(item?.id||null);setFormError('');setDraft(item?{student_id:item.student_id,kind:item.kind,subject:item.subject,title:item.title,instructions:item.instructions,due_date:item.due_date,source_id:item.source_id}:{...emptyDraft(),student_id:data?.students[0]?.id||''});setFormOpen(true);}
 async function save(e:FormEvent){e.preventDefault();if(savingRef.current)return;savingRef.current=true;setBusy(true);setFormError('');try{await request(editing?`/${editing}`:'/class-task',editing?'PUT':'POST',editing?draft:{kind:draft.kind,subject:draft.subject,title:draft.title,instructions:draft.instructions,due_date:draft.due_date});await reload();if(!editing){setTeacherStatus('');setCalendarDate(draft.due_date);}setFormOpen(false);}catch(e){setFormError((e as Error).message);}finally{savingRef.current=false;setBusy(false);}}
 async function removeTask(item:Work){if(!window.confirm(`Delete “${item.title}” for ${item.student_count||1} ${(item.student_count||1)===1?'student':'students'}? Their submissions and reviews will also be removed.`))return;setDeletingId(item.id);setError('');try{await request(`/class-task/${item.id}`,'DELETE');await reload();}catch(e){setError((e as Error).message);}finally{setDeletingId(null);}}
 const groups=teacher?groupTeacherWork(data?.items||[]):[];
 const groupState=(group:Work[]):ReviewState=>group.every(item=>item.review_state==='done')?'done':group.every(item=>item.review_state==='not_done')?'not_done':'half_done';
 const counts={not_done:groups.filter(group=>groupState(group)==='not_done').length,half_done:groups.filter(group=>groupState(group)==='half_done').length,done:groups.filter(group=>groupState(group)==='done').length};
 const awaiting=groups.filter(group=>group.some(item=>item.status==='pending'&&item.submitted_at&&!item.reviewed_at)).length;
 const visibleGroups=groups.filter(group=>(!calendarDate||group[0].due_date===calendarDate||localDay(group[0].created_at)===calendarDate||group.some(item=>item.submitted_at&&localDay(item.submitted_at)===calendarDate))&&(!teacherStatus||groupState(group)===teacherStatus));
 const visible=teacher?[]:(data?.items.filter(item=>(kind==='All'||item.kind===kind)&&(filter==='All'||(filter==='Awaiting review'?!!item.submitted_at&&!item.reviewed_at:item.status===filter.toLowerCase()))&&`${item.title} ${item.subject} ${item.student_name}`.toLowerCase().includes(query.toLowerCase()))||[]);
 return <main className={teacher?"cw-page cw-teacher":"cw-page"}><header className="cw-header"><a href={teacher?'/teacher':'/'} className="cw-brand"><span><GraduationCap size={24}/></span>SHREEHAN HQ<small>{teacher?'TEACHER WORKSPACE':'MY CLASSROOM'}</small></a><nav>{!teacher&&<a href="/">Learning hub</a>}{teacher&&<TeacherPassword/>}<button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login');}}><LogOut size={16}/>Sign out</button></nav></header><div className="cw-main"><div className="cw-heading"><div><p className="cw-eyebrow">CLASS 2 / TEACHING & LEARNING</p><h1>{teacher?'A clear view of every next step.':'Your work. Your progress.'}</h1><p>{teacher?'Plan tomorrow, review today, and keep learning moving.':'Complete your homework and assignments, then see your teacher’s feedback.'}</p></div>{teacher&&<button className="cw-primary" onClick={()=>start()} disabled={!data?.students.length}><Plus size={18}/>Create Task</button>}</div>
 {toast&&<div className="cw-toast" role="status">{toast}<button type="button" onClick={()=>setToast('')} aria-label="Dismiss notification">×</button></div>}
 {error&&<div role="alert" className="cw-error">{error}<button onClick={()=>void reload().catch(e=>setError(e.message))}>Retry</button></div>}{!data&&!error&&<p role="status">Loading your classroom…</p>}
 {data&&<>{teacher&&<button className="cw-notice" type="button" onClick={()=>{setCalendarDate('');setTeacherStatus('not_done');workRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}}><span className="cw-notice-icon"><BellRing size={20}/></span><span><strong>{counts.not_done} {counts.not_done===1?'task':'tasks'} not done</strong><small>{awaiting?`${awaiting} ${awaiting===1?'task has':'tasks have'} work awaiting review. `:''}Open a task to review each student.</small></span><span className="cw-notice-arrow">View tasks →</span></button>}<div className="cw-stats"><div><ClipboardList/><strong>{teacher?counts.not_done:data.items.filter(i=>i.status==='pending').length}</strong><span>{teacher?'Not done':'Pending'}</span></div><div><BookOpen/><strong>{teacher?counts.half_done:data.items.filter(i=>i.status==='pending'&&i.submitted_at&&!i.reviewed_at).length}</strong><span>{teacher?'Half Done':'Awaiting review'}</span></div><div><CheckCircle2/><strong>{teacher?counts.done:data.items.filter(i=>i.status==='completed').length}</strong><span>{teacher?'Done':'Completed'}</span></div></div>{teacher&&<DailyFeedback/>}
 <section ref={workRef} className="cw-work">
  <div className="cw-work-heading"><h2>{teacher?'Class tasks':'Assigned to you'} <span>{teacher?visibleGroups.length:visible.length}</span></h2><button onClick={()=>void reload().catch(e=>setError(e.message))}>Refresh</button></div>
  {teacher?<><div className="cw-teacher-searches"><label>Calendar search<input type="date" aria-label="Calendar search" value={calendarDate} onChange={event=>{setCalendarDate(event.target.value);if(event.target.value)setTeacherStatus('');}}/></label><label>Status type search<select aria-label="Status type search" value={teacherStatus} onChange={event=>{setTeacherStatus(event.target.value as ReviewState|'');if(event.target.value)setCalendarDate('');}}><option value="">All statuses</option>{(['not_done','half_done','done'] as ReviewState[]).map(state=><option key={state} value={state}>{reviewLabel[state]} ({counts[state]})</option>)}</select></label></div><p className="cw-calendar-help">Use one search at a time. Choosing a date clears the status; choosing a status clears the date. Dates match creation, due, or submission.</p></>:<div className="cw-filters"><input aria-label="Search work" placeholder="Search title, subject or student" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter work type" value={kind} onChange={e=>setKind(e.target.value)}><option value="All">All work types</option><option>Homework</option><option>Assignment</option></select><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Pending','Awaiting review','Completed'].map(v=><option key={v}>{v}</option>)}</select></div>}
   {teacher?<><div className="cw-task-columns" aria-hidden="true"><span>Latest submission</span><span>Task</span><span>Type</span><span>Due</span><span>Status</span><span/></div><div className="cw-task-list">{visibleGroups.map(group=>{const submitted=latestSubmission(group);const submittedCount=group.filter(item=>item.submitted_at).length;return <details className={`cw-class-task cw-subject-${group[0].subject.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`} key={group[0].id}><summary><span className="cw-task-submitted">{submitted?<><time dateTime={localDay(submitted)}>{dateLabel(submitted)}</time><small>{submittedCount} of {group.length} students</small></>:<span className="cw-not-submitted">Not submitted</span>}</span><span className="cw-task-title"><span className="cw-subject">{group[0].subject}</span><strong>{group[0].title}</strong><small>{group.length} {group.length===1?'student':'students'}</small></span><span className="cw-task-kind">{group[0].kind}</span><time className="cw-task-due" dateTime={group[0].due_date}>{dateLabel(group[0].due_date)}</time><span className={`cw-status ${groupState(group)}`}>{reviewLabel[groupState(group)]}</span><span className="cw-task-chevron" aria-hidden="true">⌄</span></summary><div className="cw-task-detail"><div className="cw-task-detail-head"><p>{group[0].instructions||'No extra instructions.'}</p><button type="button" className="cw-delete" disabled={deletingId===group[0].id} onClick={()=>void removeTask({...group[0],student_count:group.length})}>{deletingId===group[0].id?'Deleting…':'Delete record'}</button></div><div className="cw-grid">{group.map(item=><WorkCard key={`${item.id}:${item.updated_at}`} item={item} teacher reload={reload} edit={start} notify={setToast}/>)}</div></div></details>;})}</div></>:<div className="cw-grid">{visible.map(item=><WorkCard key={`${item.id}:${item.updated_at}`} item={item} teacher={false} reload={reload} edit={start} notify={setToast}/>)}</div>}
  {!(teacher?visibleGroups.length:visible.length)&&<div className="cw-empty"><BookOpen size={32}/><h3>{data.items.length?'No matching tasks.':'All caught up!'}</h3><p>{teacher?(data.students.length?'Choose another date or status, or clear the search.':'A student must activate an account before work can be assigned.'):'Your teacher’s homework and assignments will appear here.'}</p></div>}
 </section></>}
 <footer className="cw-footer">Shreehan HQ · Class 2 <span>Thoughtful teaching. Visible progress.</span></footer></div>
 {formOpen&&<div className="cw-overlay"><section ref={dialogRef} className="cw-dialog" role="dialog" aria-modal="true" aria-labelledby="cw-dialog-title"><div className="cw-work-heading"><h2 id="cw-dialog-title">{editing?'Edit task':'Create Task'}</h2><button disabled={busy} onClick={()=>setFormOpen(false)} aria-label="Close work form">✕</button></div><p>{editing?'Update this student’s task.':'This task will be assigned to every active student. Due date defaults to tomorrow in Bangladesh.'}</p><form onSubmit={save}><fieldset disabled={busy}><label>Work type<select disabled={!!editing||!!draft.source_id} value={draft.kind} onChange={e=>change('kind',e.target.value)}><option>Homework</option><option>Assignment</option></select></label><div className="cw-form-grid"><label>Subject<select value={draft.subject} onChange={e=>change('subject',e.target.value)}>{data?.subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Due date<input type="date" required value={draft.due_date} onChange={e=>change('due_date',e.target.value)}/></label></div><label>Title<input autoFocus required maxLength={200} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="e.g. Practise multiplication tables"/></label><label>Instructions<textarea maxLength={10000} value={draft.instructions} onChange={e=>change('instructions',e.target.value)} placeholder="What should the student complete?"/></label><p className="cw-help">Saved in this classroom for every active student.</p>{formError&&<p role="alert" className="cw-error">{formError}</p>}<div className="cw-actions"><button className="cw-primary" disabled={!draft.title.trim()||(!editing&&!data?.students.length)}>{busy?'Saving…':editing?'Save changes':'Create Task'}</button><button type="button" onClick={()=>setFormOpen(false)}>Cancel</button></div></fieldset></form></section></div>}
 </main>;
}
