'use client';

import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { BookOpen, CheckCircle2, ClipboardList, GraduationCap, LogOut, Mail, Plus, Star } from 'lucide-react';
import './coursework.css';

type Work = {id:string;student_id:string;student_name:string;kind:string;subject:string;title:string;instructions:string;due_date:string;source_id:string|null;source_url:string;status:string;score:number|null;remarks:string;submission:string;submitted_at:string|null;reviewed_at:string|null;updated_at:string};
type Source = {id:string;title:string;instructions:string;kind:string;subject:string;url:string};
type Data = {role:string;items:Work[];students:{id:string;username:string}[];subjects:string[]};
type Draft = {student_id:string;kind:string;subject:string;title:string;instructions:string;due_date:string;source_id:string|null};
function tomorrow() {const date = new Date(new Date().toLocaleString('en-US', {timeZone:'Asia/Dhaka'}));date.setDate(date.getDate()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
const emptyDraft = ():Draft => ({student_id:'',kind:'Homework',subject:'Mathematics',title:'',instructions:'',due_date:tomorrow(),source_id:null});
async function request(path:string, method='GET', body?:unknown) {
 const response = await fetch(`/api/coursework${path}`, {method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
 const value = await response.json();
 if (!response.ok) throw new Error(value.error || (response.status===422?'Check the fields and try again.':'Unable to load your work.'));
 return value;
}
function Stars({value,onChange}:{value:number|null;onChange?:(score:number|null)=>void}) {
 const [hover,setHover]=useState<number|null>(null);
 return <div className="cw-rating"><div className="cw-stars" role={onChange?'group':'img'} aria-label={`Rating: ${value??'not rated'} out of 10`} onMouseLeave={()=>setHover(null)}>{Array.from({length:10},(_,i)=>onChange?<button key={i} type="button" aria-label={`Rate ${i+1} out of 10`} aria-pressed={value===i+1} onFocus={()=>setHover(i+1)} onBlur={()=>setHover(null)} onMouseEnter={()=>setHover(i+1)} onClick={()=>onChange(i+1)}><Star size={20} fill={i<(hover??value??0)?'currentColor':'none'}/></button>:<Star key={i} size={17} fill={i<(value??0)?'currentColor':'none'}/> )}</div><span>{hover??value??'—'}/10</span>{onChange&&value!==null&&<button type="button" className="cw-text-button" onClick={()=>onChange(null)}>Clear</button>}</div>;
}
function WorkCard({item,teacher,reload,edit}:{item:Work;teacher:boolean;reload:()=>Promise<void>;edit:(item:Work)=>void}) {
 const [status,setStatus]=useState(item.status),[score,setScore]=useState(item.score),[remarks,setRemarks]=useState(item.remarks),[submission,setSubmission]=useState(item.submission),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const dirty=status!==item.status||score!==item.score||remarks!==item.remarks;
 async function run(path:string,method:string,body:unknown,success:string) {setBusy(true);setError('');setMessage('');try {const result=await request(path,method,body);setMessage(result.message||success);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="cw-card"><div className="cw-card-top"><span className="cw-subject">{item.subject}</span><span className={`cw-status ${item.status}`}>{item.status==='completed'?'Completed':item.submitted_at&&!item.reviewed_at?'Awaiting review':'Pending'}</span></div><h3>{item.title}</h3><p className="cw-meta">{item.kind} · {teacher?`${item.student_name} · `:''}Due {item.due_date}</p><p className="cw-copy">{item.instructions||'Follow your teacher’s instructions.'}</p>{item.source_url&&<a className="cw-source" href={item.source_url} target="_blank" rel="noreferrer">Open original Notion work ↗</a>}
 {item.submitted_at&&<div className="cw-submission"><strong>Student submission</strong><p>{item.submission}</p><small>Submitted {new Date(item.submitted_at).toLocaleString()}</small></div>}
 {teacher?<form onSubmit={e=>{e.preventDefault();void run(`/${item.id}/review`,'PUT',{status,score,remarks},'Review saved.');}}><fieldset disabled={busy}><label>Review status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="completed">Completed</option></select></label><label>Mark · 1 lowest, 10 highest</label><Stars value={score} onChange={setScore}/><label>Comments / remarks<textarea maxLength={4000} value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Share progress and the next step…"/></label><div className="cw-actions"><button className="cw-primary" type="submit">Save review</button><button type="button" onClick={()=>edit(item)}>Edit work</button><button type="button" disabled={dirty||!item.remarks.trim()} onClick={()=>void run(`/${item.id}/email`,'POST',undefined,'Email accepted.')}><Mail size={15}/>Email remarks</button></div><small className="cw-help">{dirty?'Save your changes before emailing.':'Emails saved remarks to sun.srs86@gmail.com.'}</small></fieldset></form>:<><Stars value={item.score}/>{item.remarks&&<div className="cw-submission"><strong>Teacher remarks</strong><p>{item.remarks}</p></div>}{item.status!=='completed'&&<form onSubmit={e=>{e.preventDefault();void run(`/${item.id}/submission`,'PUT',{submission},'Work submitted for review.');}}><fieldset disabled={busy}><label>Your answer or completed work<textarea required maxLength={10000} value={submission} onChange={e=>setSubmission(e.target.value)} placeholder="Write your answers or describe the work you have completed…"/></label><button className="cw-primary" disabled={!submission.trim()}>{item.submitted_at?'Resubmit work':'Submit work'}</button></fieldset></form>}</>}
 {error&&<p className="cw-error" role="alert">{error}</p>}{message&&<p role="status" className="cw-success">{message}</p>}</article>;
}
export default function Coursework() {
 const [data,setData]=useState<Data|null>(null),[sources,setSources]=useState<Source[]>([]),[error,setError]=useState(''),[sourceError,setSourceError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[kind,setKind]=useState('All'),[student,setStudent]=useState('All'),[formOpen,setFormOpen]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const dialogRef=useRef<HTMLElement>(null);
 useEffect(()=>{
  if(!formOpen)return;
  const previous=document.activeElement as HTMLElement|null;
  const overflow=document.body.style.overflow;
  document.body.style.overflow='hidden';
  const handle=(event:KeyboardEvent)=>{
   if(event.key==='Escape'&&!busy){event.preventDefault();setFormOpen(false);}
   if(event.key==='Tab'){
    const nodes=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]');
    if(!nodes?.length)return;
    const first=nodes[0],last=nodes[nodes.length-1];
    if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
    else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
   }
  };
  document.addEventListener('keydown',handle);
  return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handle);previous?.focus();};
 },[formOpen,busy]);
 const reload=useCallback(async()=>{const value=await request('');setData(value);setError('');},[]);
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[reload]);
 useEffect(()=>{if(data?.role==='teacher')void request('/sources').then(value=>{setSources(value.items);setSourceError('');}).catch(e=>setSourceError(e.message));},[data?.role]);
 const teacher=data?.role==='teacher';
 function change(key:keyof Draft,value:string|null){setDraft(d=>({...d,[key]:value}));}
 function start(item?:Work){setEditing(item?.id||null);setFormError('');setDraft(item?{student_id:item.student_id,kind:item.kind,subject:item.subject,title:item.title,instructions:item.instructions,due_date:item.due_date,source_id:item.source_id}:{...emptyDraft(),student_id:data?.students[0]?.id||''});setFormOpen(true);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{await request(editing?`/${editing}`:'',editing?'PUT':'POST',draft);await reload();setFormOpen(false);}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 const visible=data?.items.filter(i=>(kind==='All'||i.kind===kind)&&(student==='All'||i.student_id===student)&&(filter==='All'||(filter==='Awaiting review'?!!i.submitted_at&&!i.reviewed_at:i.status===filter.toLowerCase()))&&`${i.title} ${i.subject} ${i.student_name}`.toLowerCase().includes(query.toLowerCase()))||[];
 return <main className="cw-page"><header className="cw-header"><a href={teacher?'/teacher':'/'} className="cw-brand"><span><GraduationCap size={24}/></span>SHREEHAN HQ<small>{teacher?'TEACHER WORKSPACE':'MY CLASSROOM'}</small></a><nav>{!teacher&&<a href="/">Learning hub</a>}<button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login');}}><LogOut size={16}/>Sign out</button></nav></header><div className="cw-main"><div className="cw-heading"><div><p className="cw-eyebrow">CLASS 2 / TEACHING & LEARNING</p><h1>{teacher?'A clear view of every next step.':'Your work. Your progress.'}</h1><p>{teacher?'Plan tomorrow, review today, and keep learning moving.':'Complete your homework and assignments, then see your teacher’s feedback.'}</p></div>{teacher&&<button className="cw-primary" onClick={()=>start()} disabled={!data?.students.length}><Plus size={18}/>Create work</button>}</div>
 {error&&<div role="alert" className="cw-error">{error}<button onClick={()=>void reload().catch(e=>setError(e.message))}>Retry</button></div>}{!data&&!error&&<p role="status">Loading your classroom…</p>}
 {data&&<><div className="cw-stats"><div><ClipboardList/><strong>{data.items.length}</strong><span>Total work</span></div><div><BookOpen/><strong>{data.items.filter(i=>i.submitted_at&&!i.reviewed_at&&i.status!=='completed').length}</strong><span>Awaiting review</span></div><div><CheckCircle2/><strong>{data.items.filter(i=>i.status==='completed').length}</strong><span>Completed</span></div></div><section className="cw-work"><div className="cw-work-heading"><h2>{teacher?'Homework & assignments':'Assigned to you'} <span>{visible.length}</span></h2><button onClick={()=>void reload().catch(e=>setError(e.message))}>Refresh</button></div><div className="cw-filters"><input aria-label="Search work" placeholder="Search title, subject or student" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter work type" value={kind} onChange={e=>setKind(e.target.value)}><option value="All">All work types</option><option>Homework</option><option>Assignment</option></select><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Pending','Awaiting review','Completed'].map(v=><option key={v}>{v}</option>)}</select>{teacher&&<select aria-label="Filter student" value={student} onChange={e=>setStudent(e.target.value)}><option value="All">All students</option>{data.students.map(s=><option key={s.id} value={s.id}>{s.username}</option>)}</select>}</div><div className="cw-grid">{visible.map(item=><WorkCard key={`${item.id}:${item.updated_at}`} item={item} teacher={teacher} reload={reload} edit={start}/>)}</div>{!visible.length&&<div className="cw-empty"><BookOpen size={32}/><h3>{data.items.length?'No matching work.':'Ready for a fresh start.'}</h3><p>{teacher?(data.students.length?'Create work for tomorrow, or bring existing Notion work into the review queue.':'A student must activate an account before work can be assigned.'):'Your teacher’s homework and assignments will appear here.'}</p></div>}</section></>}
 <footer className="cw-footer">Shreehan HQ · Class 2 <span>Thoughtful teaching. Visible progress.</span></footer></div>
 {formOpen&&<div className="cw-overlay"><section ref={dialogRef} className="cw-dialog" role="dialog" aria-modal="true" aria-labelledby="cw-dialog-title"><div className="cw-work-heading"><h2 id="cw-dialog-title">{editing?'Edit work':'Plan the next step'}</h2><button disabled={busy} onClick={()=>setFormOpen(false)} aria-label="Close work form">✕</button></div><p>Due date defaults to tomorrow in Bangladesh.</p><form onSubmit={save}><fieldset disabled={busy}><div className="cw-form-grid"><label>Student<select required disabled={!!editing} value={draft.student_id} onChange={e=>change('student_id',e.target.value)}>{data?.students.map(s=><option key={s.id} value={s.id}>{s.username}</option>)}</select></label><label>Work type<select disabled={!!editing||!!draft.source_id} value={draft.kind} onChange={e=>change('kind',e.target.value)}><option>Homework</option><option>Assignment</option></select></label></div>{!editing&&<label>Existing Notion work (optional)<select value={draft.source_id||''} onChange={e=>{const source=sources.find(s=>s.id===e.target.value);setDraft(d=>source?{...d,source_id:source.id,title:source.title.slice(0,200),instructions:source.instructions.slice(0,10000),kind:source.kind,subject:data?.subjects.includes(source.subject)?source.subject:d.subject}:{...d,source_id:null});}}><option value="">Create new work</option>{sources.map(s=><option key={s.id} value={s.id}>{s.kind} · {s.title}</option>)}</select>{sourceError&&<span className="cw-error">Notion sources unavailable: {sourceError}</span>}</label>}<div className="cw-form-grid"><label>Subject<select value={draft.subject} onChange={e=>change('subject',e.target.value)}>{data?.subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Due date<input type="date" required value={draft.due_date} onChange={e=>change('due_date',e.target.value)}/></label></div><label>Title<input autoFocus required maxLength={200} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="e.g. Practise multiplication tables"/></label><label>Instructions<textarea maxLength={10000} value={draft.instructions} onChange={e=>change('instructions',e.target.value)} placeholder="What should the student complete?"/></label><p className="cw-help">Saved in this classroom. Linked Notion originals remain available for reference.</p>{formError&&<p role="alert" className="cw-error">{formError}</p>}<div className="cw-actions"><button className="cw-primary" disabled={!draft.title.trim()||!draft.student_id}>{busy?'Saving…':editing?'Save changes':'Assign work'}</button><button type="button" onClick={()=>setFormOpen(false)}>Cancel</button></div></fieldset></form></section></div>}
 </main>;
}
