import {isHomeworkRoot,homeworkFromRecords} from './homework.mjs';
import {acquireLock} from './sync-lock.mjs';
import {requireDependency} from './dependencies.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import https from 'node:https';
import dns from 'node:dns/promises';
const exec=promisify(execFile);
export const root=path.resolve(process.env.NOTION_SYNC_DIR||'.notion-sync');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const plain=a=>(a||[]).map(x=>x.plain_text||x.text?.content||'').join('');
const title=p=>plain(p.title||Object.values(p.properties||{}).find(x=>x.type==='title')?.title);
const driveLinksAvailable=records=>records.some(record=>record.driveLinks?.length);
export async function read(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch(e){if(e.code==='ENOENT')return fallback;throw e}}
export async function atomic(file,value){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file+'.tmp',JSON.stringify(value));await fs.rename(file+'.tmp',file)}
export async function list(api,endpoint,body){const out=[];let cursor;do{const d=await api(endpoint+(body===undefined?`${endpoint.includes('?')?'&':'?'}page_size=100${cursor?'&start_cursor='+cursor:''}`:''),body===undefined?undefined:{...body,page_size:100,...(cursor?{start_cursor:cursor}:{})});out.push(...d.results);cursor=d.has_more?d.next_cursor:null;if(d.has_more&&!cursor)throw Error('Invalid Notion pagination')}while(cursor);return out}
export function publicAddress(ip){if(ip.includes(':'))return /^[23][0-9a-f]{0,3}:/i.test(ip);const a=ip.split('.').map(Number);return a.length===4&&![0,10,127].includes(a[0])&&a[0]<224&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&a[1]===168)&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&[18,19].includes(a[1]));}
export function googleDriveFileId(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='drive.google.com'?u.pathname.match(/^\/file\/d\/([\w-]+)\/view\/?$/)?.[1]||null:null}catch{return null}}
export async function download(url,redirects=0){const driveId=googleDriveFileId(url);if(driveId)return download(`https://drive.google.com/uc?export=download&id=${encodeURIComponent(driveId)}`,redirects);const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||redirects>5)throw Error('Unsafe attachment URL');const addresses=await dns.lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw Error('Private attachment address rejected');return new Promise((resolve,reject)=>{const req=https.get(u,{signal:AbortSignal.timeout(120000),lookup:(_host,opts,cb)=>opts.all?cb(null,addresses):cb(null,addresses[0].address,addresses[0].family)},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();download(new URL(res.headers.location,u).href,redirects+1).then(resolve,reject);return}if(res.statusCode!==200){res.resume();reject(Error('Attachment download failed'));return}const chunks=[];let bytes=0;res.on('data',b=>{bytes+=b.length;if(bytes>100*1024*1024)req.destroy(Error('Attachment exceeds 100 MB'));else chunks.push(b)});res.on('end',()=>resolve(Buffer.concat(chunks)));res.on('error',reject)});req.setTimeout(60000,()=>req.destroy(Error('Attachment timed out')));req.on('error',reject)})}
export function fileIdentity(url){const u=new URL(url);return googleDriveFileId(url)||u.pathname.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi)?.at(-1)||hash(u.origin+u.pathname).slice(0,32)}
function client(token){let last=0;return async(endpoint,body)=>{for(let attempt=0;attempt<5;attempt++){await new Promise(r=>setTimeout(r,Math.max(0,350-(Date.now()-last))));last=Date.now();const r=await fetch('https://api.notion.com/v1/'+endpoint,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,'Notion-Version':'2025-09-03','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(60000)});if(r.status===429||r.status>=500){await new Promise(resolve=>setTimeout(resolve,Math.min(60000,Number(r.headers.get('retry-after')||2**attempt)*1000)));continue}if(!r.ok){const error=Error(`Notion request failed (${r.status}) at ${endpoint.split("?")[0]}; check integration access`);error.status=r.status;throw error;}return r.json()}throw Error('Notion temporarily unavailable')}}
export async function extract(file,dir,url,kind,subject){if(kind==='File'){let text='Preview unavailable. Download the original file.';if(/\.(txt|md|csv)$/i.test(file))text=await fs.readFile(file,'utf8');return [{number:1,image:'',text,method:'File',confidence:null}]}
 let images=[],texts=[];if(kind==='PDF'){await exec('pdftoppm',['-jpeg','-scale-to','1600',file,path.join(dir,'page')],{timeout:180000});const out=await exec('pdftotext',['-layout',file,'-'],{maxBuffer:20*1024*1024});texts=out.stdout.split('\f');images=(await fs.readdir(dir)).filter(x=>/^page-\d+\.jpg$/.test(x)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]));}else images=[path.basename(file)];
 let worker;try{const pages=[];for(let i=0;i<images.length;i++){let text=texts[i]?.trim()||'',method='PDF text',confidence=null;if(text.length<40){if(!worker){const {createWorker}=requireDependency('tesseract.js');worker=await createWorker(/bangla/i.test(subject)?'ben+eng':'eng',1,{langPath:path.resolve(process.env.OCR_MODEL_DIR||'tmp/ocr-models'),cachePath:path.resolve(process.env.OCR_CACHE_DIR||'tmp/ocr-models'),gzip:false})}const r=await worker.recognize(path.join(dir,images[i]));text=r.data.text;confidence=r.data.confidence;method='OCR'}pages.push({number:i+1,image:url+'/'+images[i],text,method,confidence})}return pages}finally{await worker?.terminate()}}
export async function sync({api=client(process.env.NOTION_TOKEN),getFile=download,processFile=extract,store=root,drive,onProgress,collection=null}={}){const release=await acquireLock(store);if(!release)return;let previousStatus;try{
 const baseline=await read('data/library.json',{documents:[],records:[]});const previous=await read(path.join(store,'library.json'),await read('data/library.json',null));previousStatus=await read(path.join(store,'status.json'),{state:'starting',lastSuccess:previous.syncedAt||null});const startedAt=new Date().toISOString();async function progress(stage){const state={state:'syncing',source:'Notion + linked Google Drive',drivePending:previous.drivePending===true,startedAt,updatedAt:new Date().toISOString(),lastSuccess:previous.syncedAt||null,stage};await atomic(path.join(store,'status.json'),state);await onProgress?.(stage)}await progress('Discovering Notion pages');
 const me=await api('users/me');if(me.bot?.workspace_name!=='Shreehan')throw Error('The integration must belong to the Shreehan workspace');
 const databaseParents=new Map();const found=await list(api,'search',{});const sources=new Map(found.filter(x=>x.object==='data_source'&&!x.archived&&!x.in_trash).map(x=>[x.id,x]));const pages=new Map(found.filter(x=>x.object==='page').map(x=>[x.id,x]));
 for(const databaseId of new Set([...sources.values()].map(s=>s.parent?.database_id).filter(Boolean))){const db=await api(`databases/${databaseId}`);databaseParents.set(databaseId,db.parent?.page_id);for(const [id,source] of sources)if(source.parent?.database_id===databaseId&&(db.archived||db.in_trash||!db.data_sources.some(s=>s.id===id)))sources.delete(id);if(!db.archived&&!db.in_trash)for(const source of db.data_sources)if(!sources.has(source.id))sources.set(source.id,await api(`data_sources/${source.id}`));}
 for(const ds of sources.values())for(const p of await list(api,`data_sources/${ds.id}/query`,{}))pages.set(p.id,p);
 // Search can omit entries transiently: explicitly confirm their current state before removal.
 for(const old of previous.records)if((!collection||old.collection===collection)&&!pages.has(old.id)){try{pages.set(old.id,await api(`pages/${old.id}`))}catch(error){if(error.status!==404)throw error;}}
 const cache=await read(path.join(store,'cache.json'),{}),nextCache=collection?Object.fromEntries(Object.entries(cache).filter(([key])=>!previous.records.some(record=>record.collection===collection&&key.startsWith(record.id+':')))):{},documents=[],records=[];const seen=new Set();
 function contextFor(p, visited=new Set()) {
  if(!p||visited.has(p.id))return {collection:'Workspace',subject:''};
  visited.add(p.id);
  const name=title(p);
  const ds=sources.get(p.parent?.data_source_id);
  const ownCollection=title(ds||{}).replace(/^\d+\.\s*/,'');
  const parent=pages.get(p.parent?.page_id||p.parent?.block_id||databaseParents.get(p.parent?.database_id||ds?.parent?.database_id));
  const inherited=parent?contextFor(parent,visited):null;
  const collection=(isHomeworkRoot(p,name)||inherited?.collection==='Homework'?'Homework':'') || ownCollection || (name==='Unseen Paper'?'Unseen Paper':inherited?.collection) || previous.records.find(r=>r.id===p.id)?.collection || 'Workspace';
  const subjectProperty=Object.entries(p.properties||{}).find(([key])=>/^subject$/i.test(key))?.[1];
  const explicit=subjectProperty?.select?.name||subjectProperty?.multi_select?.[0]?.name||plain(subjectProperty?.rich_text);
  const subject=explicit || (inherited?.collection==='Unseen Paper'&&inherited.subject?inherited.subject:name==='Unseen Paper'?'':name);
  return {collection,subject};
 }
 for(const p of pages.values()){if(p.archived||p.in_trash)continue;const context=contextFor(p);if(collection&&context.collection!==collection)continue;await progress('Reading Notion records');const pageCollection=context.collection;const oldRecord=previous.records.find(r=>r.id===p.id);const name=title(p)||oldRecord?.title||'Untitled';const subject=context.subject||name;const files=[],driveLinks=[],lines=[],contentBlocks=[];
 for(const prop of Object.values(p.properties||{})){if(prop.type==='files')for(const f of prop.files){const url=f.file?.url||f.external?.url;if(f.external&&/^https:\/\/drive\.google\.com\//.test(url||''))driveLinks.push(url);if(!f.external||!/^https:\/\/drive\.google\.com\//.test(url||'')||googleDriveFileId(url))files.push({url,name:/^https?:\/\//.test(f.name||'')?null:f.name,external:Boolean(f.external),driveUrl:googleDriveFileId(url)?url:null});}if(prop.type==='rich_text')lines.push(plain(prop.rich_text));}
 async function blocks(id,visited=new Set(),level=0){if(visited.has(id))return;visited.add(id);for(const b of await list(api,`blocks/${id}/children`)){const v=b[b.type]||{};const text=v.cells?v.cells.map(plain).join(' | '):plain(v.rich_text);if(text.trim())contentBlocks.push({id:b.id,type:b.type,text,level,...(b.type==='to_do'?{checked:Boolean(v.checked)}:{})});if(v.rich_text)lines.push(plain(v.rich_text));if(v.cells)lines.push(v.cells.map(plain).join(' | '));if(['file','pdf','image','audio','video'].includes(b.type))files.push({url:v.file?.url||v.external?.url,name:v.name||plain(v.caption),edited:b.last_edited_time,external:Boolean(v.external)});if(b.has_children&&!['child_page','child_database'].includes(b.type))await blocks(b.id,visited,level+1);if(b.type==='synced_block'&&v.synced_from?.block_id)await blocks(v.synced_from.block_id,visited,level+1);if(b.type==='child_page'&&!pages.has(b.id))pages.set(b.id,await api(`pages/${b.id}`));if(b.type==='child_database'){const db=await api(`databases/${b.id}`);databaseParents.set(b.id,db.parent?.page_id);for(const source of db.data_sources||[]){if(!sources.has(source.id)){const full=await api(`data_sources/${source.id}`);sources.set(source.id,full);for(const child of await list(api,`data_sources/${source.id}/query`,{}))pages.set(child.id,child)}}}}}
 await blocks(p.id);const body=lines.filter(Boolean).join('\n');const template='Background\nContext, objectives, and scope of the document\nAnalysis\nResearch findings, data insights, and key considerations\nRecommendations\nProposed solutions, strategies, and next steps\nImplementation\nAction items, timeline, and resource requirements';if(!title(p)&&!files.length&&(!body||body===template))continue;
 records.push({id:p.id,title:name,collection:pageCollection,subject,url:p.url,body,blocks:contentBlocks,driveLinks,completed:Object.values(p.properties||{}).find(v=>v.type==='checkbox')?.checkbox??null,templateOnly:false,topics:body,date:Object.values(p.properties||{}).find(v=>v.type==='date')?.date?.start||''});
 for(const f of files){await progress('Importing attachments');if(!f.url)throw Error('An attachment has no downloadable URL');const id=fileIdentity(f.url);if(seen.has(id))continue;seen.add(id);const old=previous.documents.find(d=>d.id===id);const key=p.id+':'+id;let doc;if(old&&!f.external&&cache[key]===p.last_edited_time+'|'+hash(JSON.stringify(files.map(f=>({name:f.name,edited:f.edited,url:new URL(f.url).origin+new URL(f.url).pathname}))))&&!old.processingError)doc={...old};else{const bytes=await getFile(f.url);const sha256=hash(bytes);if(f.driveUrl&&/\.pdf$/i.test(f.name||'')&&bytes.subarray(0,4).toString()!=='%PDF')throw Error('Linked Drive PDF did not return a PDF');if(old?.sha256===sha256&&!old.processingError)doc={...old};else{const fallback=bytes.subarray(0,4).toString()==='%PDF'?'.pdf':'.bin';const filename=f.name||(f.driveUrl?`${pageCollection==='Syllabus'?'syllabus':name.replaceAll(/[^\w-]+/g,'-').toLowerCase()}${fallback}`:decodeURIComponent(new URL(f.url).pathname.split('/').at(-1))||'document');const ext=path.extname(filename).toLowerCase().replace(/[^.a-z0-9]/g,'')||fallback;const folder=id+'-'+sha256.slice(0,16),dir=path.join(store,'assets',folder);await fs.mkdir(dir,{recursive:true});const local=path.join(dir,'original'+ext),url='/api/documents/'+folder;await fs.writeFile(local,bytes);const kind=ext==='.pdf'?'PDF':/\.(png|jpe?g|webp|gif|bmp|tiff?)$/.test(ext)?'Image':'File';let extracted,processingError;try{extracted=await processFile(local,dir,url,kind,subject)}catch{processingError='Text extraction pending; original file is available. Retrying next sync.';extracted=[{number:1,image:kind==='Image'?url+'/original'+ext:'',text:processingError,method:'Pending',confidence:null}]}doc={id,filename,url:url+'/original'+ext,kind,bytes:bytes.length,sha256,pages:extracted,...(processingError?{processingError}:{})}}}const original=baseline.documents.find(d=>d.id===id);const sourceUnchanged=(doc.sourceTitle||baseline.records.find(r=>r.id===p.id)?.title)===name;const displayTitle=sourceUnchanged?(original?.title||doc.title||name):(files.length>1?`${name} · ${doc.filename}`:name);documents.push({...doc,filename:f.name||doc.filename,title:displayTitle,sourceTitle:name,collection:pageCollection,subject,notionUrl:p.url,...(f.driveUrl?{driveUrl:f.driveUrl}:{})});nextCache[key]=p.last_edited_time+'|'+hash(JSON.stringify(files.map(f=>({name:f.name,edited:f.edited,url:new URL(f.url).origin+new URL(f.url).pathname}))));}
 }
 let drivePending=collection?previous.drivePending===true:false,publicCheckHour=collection?previous.publicCheckHour:null;
 if(!collection&&driveLinksAvailable(records)){
   const {hasDriveCredentials,hasDriveApiKey,driveClient,publicSubjectClient,syncDrive,sourceFolderId}=await import('./drive-sync.mjs');
   const authorized=Boolean(drive)||hasDriveCredentials();
   const apiKeyAccess=!authorized&&hasDriveApiKey();
   const publicClient=authorized?null:await publicSubjectClient(records);
   drivePending=!(authorized||apiKeyAccess);
   if(authorized||apiKeyAccess||publicClient.knownFiles){
     await progress(authorized?'Reading Drive files linked from Notion':apiKeyAccess?'Discovering publicly accessible Drive folder files':'Reading known public Subject Materials files');
     publicCheckHour=Math.floor(Date.now()/3600000);
     const clientForSync=drive|| (authorized?null:apiKeyAccess?driveClient(null):publicClient);
     let imported;
     try {
       imported=await syncDrive({client:clientForSync,store,folderId:sourceFolderId,publish:false,previousLibrary:previous,onProgress:stage=>progress(`Drive: ${stage}`),processFile,forceRefresh:!authorized&&!apiKeyAccess&&previous.publicCheckHour!==publicCheckHour});
     } catch(error) {
       if(!apiKeyAccess) throw error;
       // A Google API key is not user authentication. It can enumerate a folder only
       // when Drive makes that folder public; retain Notion/direct-file imports if not.
       drivePending=true;
       if(publicClient.knownFiles) imported=await syncDrive({client:publicClient,store,folderId:sourceFolderId,publish:false,previousLibrary:previous,onProgress:stage=>progress(`Drive public fallback: ${stage}`),processFile,forceRefresh:previous.publicCheckHour!==publicCheckHour});
     }
     for(const doc of imported?.documents||[]){const parent=records.find(r=>r.driveLinks.length&&r.collection==='Subject Materials'&&r.subject===doc.subject)||records.find(r=>r.driveLinks.length&&r.collection==='Syllabus'&&doc.collection==='Syllabus');const merged={...doc,notionUrl:parent?.url||doc.notionUrl};const index=documents.findIndex(other=>other.id===doc.id);if(index>=0)documents[index]=merged;else documents.push(merged);}
   }
 }
 const recordIds=new Set(records.map(item=>item.id)),documentIds=new Set(documents.map(item=>item.id));
 const allRecords=collection?[...previous.records.filter(item=>item.collection!==collection&&!recordIds.has(item.id)),...records]:records;
 const allDocuments=collection?[...previous.documents.filter(item=>item.collection!==collection&&!documentIds.has(item.id)),...documents]:documents;
 const now=new Date().toISOString();const snapshot={...previous,sourceType:'notion_drive',sourceFolderId:process.env.GOOGLE_DRIVE_FOLDER_ID||'1pg3lbrlzwxJClmKCMQEpZg-9aMIrHnwr',publicCheckHour,importedAt:collection?previous.importedAt:now,syncedAt:collection?previous.syncedAt:now,expectedAttachments:allDocuments.length,documents:allDocuments,records:allRecords,homework:homeworkFromRecords(allRecords),missing:[],ocrPending:allDocuments.filter(d=>d.processingError).length,drivePending,scope:'Shreehan Notion pages and the linked Class II half-yearly Drive folder.'};await atomic(path.join(store,'library.json'),snapshot);await atomic(path.join(store,'cache.json'),nextCache);await atomic(path.join(store,'status.json'),collection?previousStatus:{state:drivePending||snapshot.ocrPending?'partial':'ok',source:'Notion + linked Google Drive',updatedAt:now,lastSuccess:now,documents:allDocuments.length,records:allRecords.length,ocrPending:snapshot.ocrPending,drivePending,message:drivePending?'Known public files are available; new folder files need a server-side Drive credential.':''});return snapshot;
 }catch(e){if(collection&&previousStatus)await atomic(path.join(store,'status.json'),previousStatus);else{const old=await read(path.join(store,'library.json'),{});await atomic(path.join(store,'status.json'),{state:'error',lastSuccess:old.syncedAt||null,message:'Sync failed. The saved library is still available. Check server logs and Notion integration access.'})}throw e}finally{await release()}}
