import {test,expect} from '@playwright/test';

test.skip(process.env.E2E_CLASSROOM!=='1','Requires the isolated classroom fixture.');

test('shuvro administers users from the admin page',async({browser})=>{
 const context=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await context.newPage();
 await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('shuvro');
 await page.getByLabel('Password',{exact:true}).fill('classroom-test');
 await page.getByRole('button',{name:'Enter my workspace'}).click();
 await expect(page).toHaveURL(/\/admin$/);
 await expect(page.getByRole('heading',{name:'Manage users'})).toBeVisible();
 await expect(page.getByText('shuvro · You')).toBeVisible();
 await page.getByRole('button',{name:'Add user'}).click();
 const dialog=page.getByRole('dialog',{name:'Add user'});
 await dialog.getByLabel('Username').fill('new_student');
 await dialog.getByLabel('Email').fill('new@example.test');
 await dialog.getByLabel('Role').selectOption('student');
 await dialog.getByLabel('Password').fill('new-pass');
 await dialog.getByRole('button',{name:'Create user'}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByText('new_student',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit new_student'}).click();
 const edit=page.getByRole('dialog',{name:'Edit user'});
 await edit.getByLabel('Username').fill('new_teacher');
 await edit.getByLabel('Role').selectOption('teacher');
 await edit.getByRole('button',{name:'Save changes'}).click();
 await expect(edit).not.toBeVisible();
 await expect(page.getByText('new_teacher',{exact:true})).toBeVisible();
 page.once('dialog',confirmation=>confirmation.accept());
 await page.getByRole('button',{name:'Delete new_teacher'}).click();
 await expect(page.getByText('new_teacher',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Menu access'}).click();
 await expect(page.getByRole('heading',{name:'Access by role'})).toBeVisible();
 await page.getByRole('checkbox',{name:'student Document library'}).uncheck();
 const studentContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const student=await studentContext.newPage();
 await studentContext.request.post('/api/auth/login',{data:{username:'classroom_student',password:'classroom-test'}});
 await student.goto('/');
 await expect(student.getByRole('link',{name:/Document library/})).toHaveCount(0);
 await student.goto('/library');
 await expect(student).toHaveURL(/:8018\/$/);
 await studentContext.close();
 await page.getByRole('checkbox',{name:'student Document library'}).check();
 await page.getByRole('button',{name:'Accounts'}).click();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/admin-users-mobile.png',fullPage:true});
 await context.close();
});
