import {test,expect} from '@playwright/test';

test.skip(process.env.E2E_CLASSROOM!=='1','Requires the isolated classroom fixture.');

test('shuvro administers users from the admin page',async({browser})=>{
 const context=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await context.newPage();
 await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('shuvro');
 await page.getByLabel('Password',{exact:true}).fill('classroom-test');
 await page.getByRole('button',{name:'Enter my workspace'}).click();
 await expect(page).toHaveURL(/\/admin$/);
 await expect(page.getByRole('heading',{name:'Manage users'})).toBeVisible();
 await expect(page.getByText('shuvro · You')).toBeVisible();
 await page.getByRole('button',{name:'Add user'}).click();
 const dialog=page.getByRole('dialog',{name:'Add user'});
 await dialog.getByLabel('Username').fill('new_student');
 await dialog.getByLabel('Email').fill('new@example.test');
 await dialog.getByLabel('Role').selectOption('student');
 await dialog.getByLabel('Password').fill('new-pass');
 await dialog.getByRole('button',{name:'Create user'}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByText('new_student',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit new_student'}).click();
 const edit=page.getByRole('dialog',{name:'Edit user'});
 await edit.getByLabel('Username').fill('new_teacher');
 await edit.getByLabel('Role').selectOption('teacher');
 await edit.getByRole('button',{name:'Save changes'}).click();
 await expect(edit).not.toBeVisible();
 await expect(page.getByText('new_teacher',{exact:true})).toBeVisible();
 page.once('dialog',confirmation=>confirmation.accept());
 await page.getByRole('button',{name:'Delete new_teacher'}).click();
 await expect(page.getByText('new_teacher',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Menu access'}).click();
 await expect(page.getByRole('heading',{name:'Access by role'})).toBeVisible();
 await page.getByRole('checkbox',{name:'student Document library'}).uncheck();
 const studentContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const student=await studentContext.newPage();
 await studentContext.request.post('/api/auth/login',{data:{username:'classroom_student',password:'classroom-test'}});
 await student.goto('/');
 await expect(student.getByRole('link',{name:/Document library/})).toHaveCount(0);
 await student.goto('/library');
 await expect(student).toHaveURL(/:8018\/$/);
 await studentContext.close();
 await page.getByRole('checkbox',{name:'student Document library'}).check();
 await page.getByRole('button',{name:'Accounts'}).click();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/admin-users-mobile.png',fullPage:true});
 await context.close();
});

test('teacher daily feedback appears as a full admin notification',async({browser})=>{
 const teacherContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const teacher=await teacherContext.newPage();
 await teacherContext.request.post('/api/auth/login',{data:{username:'teacher',password:'classroom-test'}});
 await teacher.goto('/teacher');
 const note=`Shreehan finished reading today.\nPlease watch his spelling practice ${Date.now()}.`;
 await teacher.getByLabel('Today’s feedback').fill(note);
 await teacher.getByRole('button',{name:'Send to admin'}).click();
 const confirmation=teacher.getByRole('dialog',{name:'Feedback sent'});
 await expect(confirmation).toBeVisible();
 await expect(confirmation.getByText(note,{exact:true})).toBeVisible();
 await expect(teacher.getByLabel('Today’s feedback')).toHaveValue('');
 await Promise.all([teacher.waitForEvent('load'),confirmation.getByRole('button',{name:'Done'}).click()]);
 await expect(teacher.getByLabel('Today’s feedback')).toHaveValue('');
 await expect(teacher.getByRole('button',{name:'Notify Guardian'})).toBeDisabled();
 const revisedNote=`${note}\nReading has improved.`;
 await teacher.getByLabel('Today’s feedback').fill(revisedNote);
 await teacher.getByRole('button',{name:'Notify Guardian'}).click();
 const revision=teacher.getByRole('dialog',{name:'Feedback updated'});
 await expect(revision.getByText('Previous update')).toBeVisible();
 await expect(revision.getByText(note,{exact:true})).toBeVisible();
 await expect(revision.getByText('New update')).toBeVisible();
 await expect(revision.getByText(revisedNote,{exact:true})).toBeVisible();
 await expect(teacher.getByLabel('Today’s feedback')).toHaveValue('');
 await teacher.screenshot({path:'../tmp/teacher-feedback-confirmation.png',fullPage:true});
 await Promise.all([teacher.waitForEvent('load'),revision.getByRole('button',{name:'Done'}).click()]);
 await expect(teacher.getByLabel('Today’s feedback')).toHaveValue('');
 const adminContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const admin=await adminContext.newPage();
 await adminContext.request.post('/api/auth/login',{data:{username:'shuvro',password:'classroom-test'}});
 await admin.goto('/admin');
 await admin.getByRole('button',{name:/Teacher updates/}).click();
 await expect(admin.getByRole('heading',{name:'Notifications'})).toBeVisible();
 const notification=admin.locator('.admin-feedback-item').filter({hasText:revisedNote});
 await expect(notification).toHaveCount(1);
 await expect(notification).toContainText('teacher');
 await expect(notification.getByText(revisedNote,{exact:true})).toBeVisible();
 await expect(admin.locator('.admin-unread')).toContainText('1');
 await notification.getByRole('button',{name:'Mark as read'}).click();
 await expect(notification.getByText('Read',{exact:true})).toBeVisible();
 await expect(admin.locator('.admin-unread')).toHaveCount(0);
 await admin.setViewportSize({width:390,height:844});
 expect(await admin.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await admin.screenshot({path:'../tmp/admin-feedback-mobile.png',fullPage:true});
 await teacherContext.close();await adminContext.close();
});
