import { test, expect } from '@playwright/test';

test.skip(process.env.E2E_CLASSROOM !== '1', 'Requires the isolated backend.tests.classroom_server fixture.');

test('teacher plans, student submits, teacher grades; desktop and mobile', async ({browser}) => {
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await ctx.newPage();
 await page.goto('/login');
 await page.getByLabel('Username', {exact:true}).fill('teacher');
 await page.getByLabel('Password', {exact:true}).fill('classroom-test');
 await page.getByRole('button',{name:'Enter my workspace',exact:true}).click();
 await expect(page).toHaveURL(/\/teacher$/);
 await expect(page.getByRole('heading',{name:'A clear view of every next step.'})).toBeVisible();
 await page.getByRole('button',{name:'Create work',exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('combobox',{name:'Subject',exact:true}).locator('option')).toHaveCount(11);
 const title=`Math practice ${Date.now()}`;
 await page.getByLabel('Title',{exact:true}).fill(title);
 await page.getByLabel('Instructions',{exact:true}).fill('Complete questions 1–5 on page 44.');
 await page.getByRole('button',{name:'Assign work',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 const card=page.locator('.cw-card').filter({hasText:title});
 await expect(card).toBeVisible();
 await page.screenshot({path:'../tmp/teacher-desktop.png',fullPage:true});
 const sc=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const student=await sc.newPage();
 await sc.request.post('/api/auth/login',{data:{username:'classroom_student',password:'classroom-test'}});
 await student.goto('/coursework');
 const studentCard=student.locator('.cw-card').filter({hasText:title});
 await studentCard.getByLabel('Your answer or completed work').fill('Completed: 2, 4, 6, 8, 10.');
 await studentCard.getByRole('button',{name:'Submit work',exact:true}).click();
 await expect(studentCard.getByText('Awaiting review',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(card.getByText('Completed: 2, 4, 6, 8, 10.',{exact:true})).toBeVisible();
 await card.getByLabel('Review status').selectOption('completed');
 await card.getByRole('button',{name:'Rate 8 out of 10',exact:true}).click();
 await card.getByLabel('Comments / remarks').fill('Good progress. Check question five again.');
 await card.getByRole('button',{name:'Save review',exact:true}).click();
 await expect(card.locator('.cw-status.completed')).toBeVisible();
 await page.reload();
 await expect(card.getByRole('button',{name:'Rate 8 out of 10',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(card.getByRole('button',{name:'Email remarks',exact:true})).toBeEnabled();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'../tmp/teacher-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Create work',exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/teacher-mobile-form.png',fullPage:true});
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await student.reload();
 await expect(studentCard.getByRole('img',{name:'Rating: 8 out of 10'})).toBeVisible();
 await expect(studentCard.getByText('Good progress. Check question five again.',{exact:true})).toBeVisible();
 await ctx.close();await sc.close();
});
