import { test, expect } from '@playwright/test';

test.skip(process.env.E2E_CLASSROOM !== '1', 'Requires the isolated backend.tests.classroom_server fixture.');

test('teacher sees one class task and filters its completion state', async ({browser}) => {
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await ctx.newPage();
 await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('teacher');
 await page.getByLabel('Password',{exact:true}).fill('classroom-test');
 await page.getByRole('button',{name:'Enter my workspace',exact:true}).click();
 await expect(page).toHaveURL(/\/teacher$/);
 await expect(page.getByRole('button',{name:'Create Task',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:/tasks? not done/})).toBeVisible();
 await expect(page.getByRole('combobox',{name:'Filter student'})).toHaveCount(0);
 await expect(page.getByRole('combobox',{name:'Filter status'}).locator('option')).toHaveCount(4);
 const initialPending=Number((await page.locator('.cw-notice strong').innerText()).match(/^\d+/)?.[0]);
 await page.getByRole('button',{name:'Create Task',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog).toBeVisible();
 await expect(dialog.getByText('This task will be assigned to every active student.',{exact:false})).toBeVisible();
 await expect(dialog.getByText('Student',{exact:true})).toHaveCount(0);
 await expect(dialog.getByText('Existing Notion work (optional)')).toHaveCount(0);
 await expect(dialog.getByRole('combobox',{name:'Subject',exact:true}).locator('option')).toHaveCount(11);
 const title=`Science task ${Date.now()}`;
 await dialog.getByRole('combobox',{name:'Work type'}).selectOption('Assignment');
 await dialog.getByRole('combobox',{name:'Subject',exact:true}).selectOption('Science');
 await dialog.getByLabel('Title',{exact:true}).fill(title);
 await dialog.getByLabel('Instructions',{exact:true}).fill('Describe a rock from your science lesson.');
 await dialog.getByRole('button',{name:'Create Task',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 const task=page.locator('.cw-class-task').filter({hasText:title});
 await expect(task).toHaveCount(1);
 await expect(task).toHaveClass(/cw-subject-science/);
 await expect(task.locator('summary')).toContainText('2 students');
 await expect(page.locator('.cw-notice strong')).toContainText(`${initialPending+1} task`);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('Completed');
 await expect(task).toHaveCount(0);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('Not Done');
 await expect(task).toHaveCount(1);
 await task.locator('summary').click();
 const card=task.locator('.cw-card').filter({has:page.getByText('classroom_student',{exact:true})});
 await expect(task.locator('.cw-card')).toHaveCount(2);
 await page.screenshot({path:'../tmp/teacher-updated-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 const cardPosition=await task.boundingBox();
 expect(cardPosition?.y).toBeLessThan(680);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/teacher-compact-mobile-pending.png',fullPage:true});
 await page.setViewportSize({width:1280,height:800});
 const studentContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const student=await studentContext.newPage();
 await studentContext.request.post('/api/auth/login',{data:{username:'classroom_student',password:'classroom-test'}});
 await student.goto('/coursework');
 const studentCard=student.locator('.cw-card').filter({hasText:title});
 await studentCard.getByLabel('Your answer or completed work').fill('Granite is a hard rock.');
 await studentCard.getByRole('button',{name:'Submit work',exact:true}).click();
 await expect(studentCard.getByText('Awaiting review',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(card.getByText('Granite is a hard rock.',{exact:true})).toBeVisible();
 await expect(page.locator('.cw-notice small')).toContainText('task has work awaiting review');
 await card.getByRole('button',{name:'Rate 8 out of 10'}).click();
 await expect(card.getByRole('button',{name:'Rate 8 out of 10'})).toHaveAttribute('aria-pressed','true');
 await card.getByLabel('Comments / remarks').fill('Good observation.');
 await card.getByLabel('Review status').selectOption('completed');
 await card.getByRole('button',{name:'Save review'}).click();
 await expect(task.locator('summary')).toContainText('Not Done');
 await expect(page.locator('.cw-notice strong')).toContainText(`${initialPending+1} task`);
 await page.reload();
 await expect(page.locator('.cw-class-task').filter({hasText:title})).toHaveCount(1);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('Completed');
 await expect(page.locator('.cw-class-task').filter({hasText:title})).toHaveCount(0);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('All');
 const remainingTask=page.locator('.cw-class-task').filter({hasText:title});
 await remainingTask.locator('summary').click();
 const remainingCard=remainingTask.locator('.cw-card').filter({has:page.getByText('classroom_student_two',{exact:true})});
 await remainingCard.getByLabel('Review status').selectOption('completed');
 await remainingCard.getByRole('button',{name:'Save review'}).click();
 await expect(remainingTask.locator('summary')).toContainText('Completed');
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('Completed');
 await expect(remainingTask).toHaveCount(1);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('Not Done');
 await expect(remainingTask).toHaveCount(0);
 await page.getByRole('combobox',{name:'Filter status'}).selectOption('All');
 // Verify the combined email action without contacting the real mail provider.
 await page.route('**/api/coursework/*/email',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'Email accepted.'})}));
 await page.getByRole('button',{name:'Create Task',exact:true}).click();
 const mailTitle=`Poetry task ${Date.now()}`;
 await dialog.getByRole('combobox',{name:'Subject',exact:true}).selectOption('Poetry');
 await dialog.getByLabel('Title',{exact:true}).fill(mailTitle);
 await dialog.getByRole('button',{name:'Create Task',exact:true}).click();
 const mailTask=page.locator('.cw-class-task').filter({hasText:mailTitle});
 await mailTask.locator('summary').click();
 const mailCard=mailTask.locator('.cw-card').filter({has:page.getByText('classroom_student',{exact:true})});
 await mailCard.getByLabel('Comments / remarks').fill('Read with expression.');
 await mailCard.getByLabel('Review status').selectOption('completed');
 await mailCard.getByRole('button',{name:'Save & email'}).click();
 await expect(mailTask).toBeVisible();
 await student.reload();
 await expect(studentCard.getByRole('img',{name:'Rating: 8 out of 10'})).toBeVisible();
 await expect(student.locator('.cw-card').filter({hasText:mailTitle}).getByText('Read with expression.',{exact:true})).toBeVisible();
 await expect(studentCard.getByText('Good observation.',{exact:true})).toBeVisible();
 page.once('dialog', dialog=>dialog.accept());
 await mailTask.getByRole('button',{name:'Delete record'}).click();
 await expect(mailTask).toHaveCount(0);
 await student.reload();
 await expect(student.locator('.cw-card').filter({hasText:mailTitle})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'../tmp/teacher-updated-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Create Task',exact:true}).click();
 await expect(dialog).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/teacher-updated-mobile-form.png',fullPage:true});
 await dialog.getByRole('button',{name:'Cancel'}).click();
 await ctx.close();await studentContext.close();
});
