import { test, expect } from '@playwright/test';

test.skip(process.env.E2E_CLASSROOM !== '1', 'Requires the isolated backend.tests.classroom_server fixture.');

test('teacher sees one class task and filters its completion state', async ({browser}) => {
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await ctx.newPage();
 await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('teacher');
 await page.getByLabel('Password',{exact:true}).fill('classroom-test');
 await page.getByRole('button',{name:'Enter my workspace',exact:true}).click();
 await expect(page).toHaveURL(/\/teacher$/);
 let guardianRequests=0;
 await page.route('**/api/coursework/*/email',route=>{guardianRequests++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'Email accepted.'})});});
 await expect(page.getByRole('button',{name:'Assign task',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:/tasks? not done/})).toBeVisible();
 await expect(page.getByRole('combobox',{name:'Filter student'})).toHaveCount(0);
 await expect(page.getByLabel('Search work')).toHaveCount(0);
 await expect(page.getByLabel('Calendar search')).toBeVisible();
 await expect(page.getByLabel('Status type search')).toHaveValue('');
 await expect(page.getByLabel('Filter work type')).toHaveCount(0);
 await expect(page.getByRole('tab')).toHaveCount(0);
 await expect(page.locator('.cw-task-columns')).toContainText('Latest submission');
 await expect(page.getByRole('combobox',{name:'Filter status'})).toHaveCount(0);
 const searches=page.locator('.cw-teacher-searches');
 expect(await searches.locator('label').allTextContents()).toEqual(expect.arrayContaining([expect.stringContaining('Calendar search'),expect.stringContaining('Status type search')]));
 await expect(page.getByRole('navigation').getByRole('button',{name:'Change password'})).toBeVisible();
 expect(await page.getByRole('navigation').getByRole('button').allTextContents()).toEqual(['Change password','Sign out']);
 await expect(page.getByLabel('Calendar search')).toHaveValue(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Dhaka'}));
 const initialPending=Number((await page.locator('.cw-notice strong').innerText()).match(/^\d+/)?.[0]);
 await page.getByRole('button',{name:'Assign task',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog).toBeVisible();
 await expect(dialog.getByRole('heading',{name:'Assign task'})).toBeVisible();
 expect(await dialog.evaluate(element=>getComputedStyle(element).backgroundImage)).toContain('linear-gradient');
 expect(await dialog.evaluate(element=>getComputedStyle(element).backgroundColor)).toBe('rgb(252, 252, 252)');
 expect(await dialog.evaluate(element=>getComputedStyle(element).borderTopColor)).toBe('rgb(236, 173, 10)');
 await expect(dialog.getByText('This task will be assigned to every active student.',{exact:false})).toBeVisible();
 await expect(dialog.getByText('Student',{exact:true})).toHaveCount(0);
 await expect(dialog.getByText('Existing Notion work (optional)')).toHaveCount(0);
 await expect(dialog.getByRole('combobox',{name:'Subject',exact:true}).locator('option')).toHaveCount(11);
 const title=`Science task ${Date.now()}`;
 await dialog.getByRole('combobox',{name:'Work type'}).selectOption('Assignment');
 await dialog.getByRole('combobox',{name:'Subject',exact:true}).selectOption('Science');
 await dialog.getByLabel('Title',{exact:true}).fill(title);
 await dialog.getByLabel('Instructions',{exact:true}).fill('Describe a rock from your science lesson.');
 const dueDate=await dialog.getByLabel('Due date').inputValue();
 await dialog.getByRole('button',{name:'Assign task',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 const task=page.locator('.cw-class-task').filter({hasText:title});
 await expect(page.getByLabel('Calendar search')).toHaveValue(dueDate);
 await expect(page.getByLabel('Status type search')).toHaveValue('');
 await expect(task).toHaveCount(1);
 await page.reload();
 await expect(page.getByLabel('Calendar search')).toHaveValue(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Dhaka'}));
 await expect(task).toHaveCount(1);
 await page.getByLabel('Calendar search').fill(dueDate);
 await expect(task).toHaveCount(1);
 await expect(task).toHaveClass(/cw-subject-science/);
 await expect(task.locator('summary')).toContainText('2 students');
 await expect(task.locator('summary .cw-task-submitted')).toContainText('Not submitted');
 await expect(task.locator('summary').getByRole('button',{name:'Delete record'})).toHaveCount(0);
 await page.getByLabel('Calendar search').fill('2030-01-01');
 await expect(task).toHaveCount(0);
 await page.getByLabel('Calendar search').fill(dueDate);
 await expect(task).toHaveCount(1);
 await expect(page.locator('.cw-notice strong')).toContainText(`${initialPending+1} task`);
 await page.getByLabel('Status type search').selectOption('done');
 await expect(page.getByLabel('Calendar search')).toHaveValue('');
 await expect(task).toHaveCount(0);
 await page.getByLabel('Calendar search').fill(dueDate);
 await expect(page.getByLabel('Status type search')).toHaveValue('');
 await expect(task).toHaveCount(1);
 await page.getByLabel('Status type search').selectOption('not_done');
 await expect(page.getByLabel('Calendar search')).toHaveValue('');
 await expect(task).toHaveCount(1);
 await task.locator('summary').click();
 await expect(task.getByRole('button',{name:'Delete record'})).toBeVisible();
 const card=task.locator('.cw-card').filter({has:page.getByText('classroom_student',{exact:true})});
 await expect(task.locator('.cw-card')).toHaveCount(2);
 await page.screenshot({path:'../tmp/teacher-updated-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 for(const name of ['Change password','Sign out']){
  const bounds=await page.getByRole('navigation').getByRole('button',{name}).boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);
 }
 await page.setViewportSize({width:320,height:700});
 const calendarBounds=await page.getByLabel('Calendar search').boundingBox();
 const statusBounds=await page.getByLabel('Status type search').boundingBox();
 expect(calendarBounds).not.toBeNull();
 expect(statusBounds).not.toBeNull();
 expect(calendarBounds!.x+calendarBounds!.width).toBeLessThan(statusBounds!.x);
 expect(statusBounds!.x+statusBounds!.width).toBeLessThanOrEqual(320);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 for(const name of ['Change password','Sign out']){
  const bounds=await page.getByRole('navigation').getByRole('button',{name}).boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(320);
 }
 await page.setViewportSize({width:390,height:844});
 await expect(page.getByRole('heading',{name:'How is Shreehan doing today?'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/teacher-compact-mobile-pending.png',fullPage:true});
 await page.setViewportSize({width:1280,height:800});
 const studentContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const student=await studentContext.newPage();
 await studentContext.request.post('/api/auth/login',{data:{username:'classroom_student',password:'classroom-test'}});
 await student.goto('/coursework');
 const studentCard=student.locator('.cw-card').filter({hasText:title});
 await studentCard.getByLabel('Your answer or completed work').fill('Granite is a hard rock.');
 await studentCard.getByRole('button',{name:'Submit work',exact:true}).click();
 await expect(studentCard.getByText('Awaiting review',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(card.getByText('Granite is a hard rock.',{exact:true})).toBeVisible();
 await expect(task.locator('summary .cw-task-submitted time')).toBeVisible();
 const submittedDay=await task.locator('summary .cw-task-submitted time').getAttribute('datetime');
 expect(submittedDay).toMatch(/^\d{4}-\d{2}-\d{2}$/);
 await page.getByLabel('Calendar search').fill(submittedDay!);
 await expect(task).toHaveCount(1);
 await page.getByLabel('Calendar search').fill(dueDate);
 await expect(page.locator('.cw-notice small')).toContainText('task has work awaiting review');
 await card.getByRole('button',{name:'Rate 8 out of 10'}).click();
 await expect(card.getByRole('button',{name:'Rate 8 out of 10'})).toHaveAttribute('aria-pressed','true');
 await student.reload();
 await expect(studentCard.getByRole('img',{name:'Rating: not rated out of 10'})).toBeVisible();
 await card.getByLabel('Comments / remarks').fill('Good observation.');
 await card.getByLabel('Review Status').selectOption('done');
 await card.getByRole('button',{name:'Save review'}).click();
 await expect(page.getByRole('status').filter({hasText:'Guardian has been notified'})).toBeVisible();
 expect(guardianRequests).toBe(1);
 await page.getByLabel('Status type search').selectOption('half_done');
 await expect(task.locator('summary')).toContainText('Half Done');
 await expect(task).toHaveCount(1);
 await task.locator('summary').click();
 await expect(card.getByLabel('Comments / remarks')).toHaveValue('');
 await expect(page.locator('.cw-notice strong')).toContainText(`${initialPending} task`);
 await page.reload();
 await page.getByLabel('Status type search').selectOption('half_done');
 await expect(page.locator('.cw-class-task').filter({hasText:title})).toHaveCount(1);
 await page.getByLabel('Status type search').selectOption('done');
 await expect(page.locator('.cw-class-task').filter({hasText:title})).toHaveCount(0);
 await page.getByLabel('Status type search').selectOption('half_done');
 const remainingTask=page.locator('.cw-class-task').filter({hasText:title});
 await remainingTask.locator('summary').click();
 const remainingCard=remainingTask.locator('.cw-card').filter({has:page.getByText('classroom_student_two',{exact:true})});
 await remainingCard.getByLabel('Review Status').selectOption('done');
 await remainingCard.getByRole('button',{name:'Save review'}).click();
 await page.getByLabel('Status type search').selectOption('done');
 await expect(remainingTask.locator('summary')).toContainText('Done');
 await expect(remainingTask).toHaveCount(1);
 await page.getByLabel('Status type search').selectOption('not_done');
 await expect(remainingTask).toHaveCount(0);

 // Verify the guardian action without contacting the real mail provider.
 await page.getByRole('button',{name:'Assign task',exact:true}).click();
 const mailTitle=`Poetry task ${Date.now()}`;
 await dialog.getByRole('combobox',{name:'Subject',exact:true}).selectOption('Poetry');
 await dialog.getByLabel('Title',{exact:true}).fill(mailTitle);
 await dialog.getByRole('button',{name:'Assign task',exact:true}).click();
 await page.getByLabel('Calendar search').fill(dueDate);
 const mailTask=page.locator('.cw-class-task').filter({hasText:mailTitle});
 await expect(mailTask).toHaveCount(1);
 await mailTask.locator('summary').click();
 const mailCard=mailTask.locator('.cw-card').filter({has:page.getByText('classroom_student',{exact:true})});
 await mailCard.getByLabel('Comments / remarks').fill('Read with expression.');
 await mailCard.getByLabel('Review Status').selectOption('done');
 await mailCard.getByRole('button',{name:'Update to Guardian'}).click();
 await expect(page.getByRole('status').filter({hasText:'Guardian has been notified'})).toBeVisible();
 await page.getByLabel('Status type search').selectOption('half_done');
 await expect(mailTask).toBeVisible();
 await mailTask.locator('summary').click();
 await expect(mailCard.getByLabel('Comments / remarks')).toHaveValue('');
 await student.reload();
 await expect(studentCard.getByRole('img',{name:'Rating: 8 out of 10'})).toBeVisible();
 await expect(student.locator('.cw-card').filter({hasText:mailTitle}).getByText('Read with expression.',{exact:true})).toBeVisible();
 await expect(studentCard.getByText('Good observation.',{exact:true})).toBeVisible();
 page.once('dialog', dialog=>dialog.accept());
 await mailTask.getByRole('button',{name:'Delete record'}).click();
 await expect(mailTask).toHaveCount(0);
 await student.reload();
 await expect(student.locator('.cw-card').filter({hasText:mailTitle})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'../tmp/teacher-updated-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Assign task',exact:true}).click();
 await expect(dialog).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../tmp/teacher-updated-mobile-form.png',fullPage:true});
 await dialog.getByRole('button',{name:'Cancel'}).click();
 await page.getByRole('navigation').getByRole('button',{name:'Change password'}).click();
 const passwordForm=page.locator('.cw-password');
 await passwordForm.getByLabel('New password').fill('teacher-new-pass');
 await passwordForm.getByLabel('Confirm password').fill('different-pass');
 await passwordForm.getByRole('button',{name:'Save password'}).click();
 await expect(passwordForm.getByRole('alert')).toContainText('Passwords do not match.');
 await ctx.close();await studentContext.close();
});

test('a failed guardian send keeps the review draft and does not claim notification',async({browser})=>{
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL});
 const page=await ctx.newPage();
 await ctx.request.post('/api/auth/login',{data:{username:'teacher',password:'classroom-test'}});
 await page.goto('/teacher');
 await page.route('**/api/coursework/*/email',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Guardian email is temporarily unavailable.'})}));
 await page.getByRole('button',{name:'Assign task',exact:true}).click();
 const dialog=page.getByRole('dialog');
 const title=`Review retry ${Date.now()}`;
 await dialog.getByLabel('Title',{exact:true}).fill(title);
 await dialog.getByLabel('Due date').fill(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Dhaka'}));
 await dialog.getByRole('button',{name:'Assign task',exact:true}).click();
 const task=page.locator('.cw-class-task').filter({hasText:title});
 await task.locator('summary').click();
 const card=task.locator('.cw-card').filter({has:page.getByText('classroom_student',{exact:true})});
 await card.getByLabel('Comments / remarks').fill('Please practise the next page.');
 await card.getByRole('button',{name:'Save review'}).click();
 await expect(card.getByRole('alert')).toContainText('Review saved, but Guardian has not been notified.');
 await expect(card.getByLabel('Comments / remarks')).toHaveValue('Please practise the next page.');
 await expect(page.getByRole('status').filter({hasText:'Guardian has been notified'})).toHaveCount(0);
 await page.unroute('**/api/coursework/*/email');
 await page.route('**/api/coursework/*/email',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'Email accepted.'})}));
 await card.getByRole('button',{name:'Update to Guardian'}).click();
 await expect(page.getByRole('status').filter({hasText:'Guardian has been notified'})).toBeVisible();
 await task.locator('summary').click();
 await expect(card.getByLabel('Comments / remarks')).toHaveValue('');
 await ctx.close();
});
